// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXSeE-Bpj5nZ_DgxT0d6I3zVwnsFOaoWg',
    appId: '1:657326886723:web:605a1db92aab5ad3c869f6',
    messagingSenderId: '657326886723',
    projectId: 'blinkit-clone-36929',
    authDomain: 'blinkit-clone-36929.firebaseapp.com',
    storageBucket: 'blinkit-clone-36929.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiRgIVA44waDYvp8zpivM4QV22Cnut4Xc',
    appId: '1:657326886723:android:a803c1ea28fac96ec869f6',
    messagingSenderId: '657326886723',
    projectId: 'blinkit-clone-36929',
    storageBucket: 'blinkit-clone-36929.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcixtY15UBnodBmD6k-3_CH_OUmY11VXE',
    appId: '1:657326886723:ios:27a34436e1492acfc869f6',
    messagingSenderId: '657326886723',
    projectId: 'blinkit-clone-36929',
    storageBucket: 'blinkit-clone-36929.firebasestorage.app',
    iosBundleId: 'com.example.blinkitClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXSeE-Bpj5nZ_DgxT0d6I3zVwnsFOaoWg',
    appId: '1:657326886723:web:68d1e6f76698f5dbc869f6',
    messagingSenderId: '657326886723',
    projectId: 'blinkit-clone-36929',
    authDomain: 'blinkit-clone-36929.firebaseapp.com',
    storageBucket: 'blinkit-clone-36929.firebasestorage.app',
  );
}
